Oversold Product
codingcab/management.products.api pull request #606
Opened 2021-08-12 07:51 UTC by rizkypujiraharja

2021-08-16 11:07 UTC, ArturHanusek requested changes

2021-08-17 08:37 UTC, ArturHanusek requested changes

2021-08-17 08:37 UTC, ArturHanusek commented on app/Modules/OversoldProductNotification/src/Listeners/SendOversoldProductNotificationListener.php
> +        SendOversoldProductMailJob::dispatch($data, $to)->onConnection('database');
onConnection shouldnt be specified, queue configuration should be left to administrator
default is database but SQS, redis etc can be also used. 
This way you hardcoding and forcing clients to use your way

2021-08-17 09:58 UTC, rizkypujiraharja commented on app/Modules/OversoldProductNotification/src/Listeners/SendOversoldProductNotificationListener.php
> +        SendOversoldProductMailJob::dispatch($data, $to)->onConnection('database');
Oh, i see

thanks for your review

2021-08-17 11:48 UTC, merged